[GLOBAL]
pants_version = "2.27.0"

backend_packages = [
  "pants.backend.experimental.python.lint.ruff.check",
  "pants.backend.python",
  "pants.backend.python.typecheck.mypy",
]

[python]
interpreter_constraints = [">=3.13"]

[test]
use_coverage = true
